# Generated by Django 3.0.5 on 2022-06-17 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='sub',
            field=models.FileField(null=True, upload_to='sub/'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='date_uploaded',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
